cache: 
  type : redis
  host : localhost
  port : 6379
spring:
  data:
    mongodb:
     host: localhost
     port: 27017
     database: studentInfo
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=studentInfo
#
#spring.cache.type=redis
#spring.redis.host=localhost
#spring.redis.port=6379
#spring.data.redis.repositories.enabled=true
#spring.redis.password= 
#
#spring.redis.lettuce.pool.max-active=7 
#spring.redis.lettuce.pool.max-idle=7
#spring.redis.lettuce.pool.min-idle=2
#spring.redis.lettuce.pool.max-wait=-1ms
#spring.redis.lettuce.shutdown-timeout=200ms
#
#spring.cache.redis.cache-null-values=false
#spring.cache.redis.time-to-live=600000

